require('plugins')
require('settings')
require('keybinds')
require('vsnip-config')
-- require('blankline-config') -- no longer using but might go back
require('colorizer-config')
-- require('lualine-config')
require('treesitter-config')
require('nvim-tree-config')
require('todo-config')
require('vimwiki-config')
require('neogit-config')
require('fzf-config')
require('lsp')
require('feline-config')
